# Generated by Django 4.1.13 on 2024-04-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField(default=0)),
                ('type', models.CharField(choices=[('CPU', 'CPU'), ('GPU', 'GPU'), ('RAM', 'RAM'), ('PSU', 'PSU'), ('Storage', 'Storage'), ('Motherboard', 'Motherboard'), ('Case', 'Case'), ('Other', 'Other')], max_length=255)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
