# Generated by Django 4.1.13 on 2024-04-17 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('receipt_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total', models.FloatField(default=0)),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='carts.cart')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='users.user')),
            ],
            options={
                'db_table': 'receipts',
            },
        ),
    ]
